### ISSUE TITLE
Injection failed on paper 1.16.5

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#119]
> [09:42:32 WARN]: [GrimAC] PacketEvents failed to inject with the Early Injector. Reverting to the Compatibility/Late Injector... This is just a warning, but please report this!
[09:42:32 WARN]: java.lang.IllegalStateException: PacketEvents failed to inject!
[09:42:32 WARN]:        at ac.grim.grimac.shaded.packetevents.injector.modern.early.EarlyChannelInjectorModern.inject(EarlyChannelInjectorModern.java:124)
[09:42:32 WARN]:        at ac.grim.grimac.shaded.packetevents.injector.GlobalChannelInjector.inject(GlobalChannelInjector.java:50)
[09:42:32 WARN]:        at ac.grim.grimac.shaded.packetevents.PacketEvents.load(PacketEvents.java:134)
[09:42:32 WARN]:        at java.lang.Thread.run(Thread.java:748)
[09:42:32 WARN]: Caused by: net.kyori.adventure.key.InvalidKeyException: Non [a-z0-9_.-] character in namespace of Key[pe-GrimAC:injector]
[09:42:32 WARN]:        at net.kyori.adventure.key.KeyImpl.<init>(KeyImpl.java:45)
[09:42:32 WARN]:        at net.kyori.adventure.key.Key.key(Key.java:117)
[09:42:32 WARN]:        at ac.grim.grimac.shaded.packetevents.injector.modern.early.PaperChannelInjector.setPaperChannelInitializeListener(PaperChannelInjector.java:48)
[09:42:32 WARN]:        at ac.grim.grimac.shaded.packetevents.injector.modern.early.EarlyChannelInjectorModern.inject(EarlyChannelInjectorModern.java:78)
[09:42:32 WARN]:        ... 3 more

Using shaded PacketEvents version be7d66d (Current latest dev commit)

**Comment by retrooper** [comment]
I appreciate you already updating to the dev commit. I am looking into it.

**Comment by retrooper** [comment]
Why can't I reproduce?

**Comment by MWHunter** [comment]
Try latest paper 1.16.5

**Comment by retrooper** [comment]
I did try with latest paper 1.16.5 latest dev build as of today.

**Comment by retrooper** [comment]
Can you test the commit I just pushed?

**Comment by MWHunter** [comment]
I changed the name of my plugin from "GrimAC" to "grimac" in plugin.yml and it now works.  The commit didn't fix it.

**Comment by retrooper** [comment]
For me setting my plugin name to "GrimAC" still worked, can you try latest paper build to see if they maybe patched it on their end?

**Comment by MWHunter** [comment]
I am on latest paper and the packetevents dev build.  It's that uppercase isn't allowed in injector names.  Set it in plugin.yml

**Comment by retrooper** [comment]
Even with an uppercase letter, for me it worked, which confuses me...

**Comment by retrooper** [comment]
Well I will try a solution, you can put it back to "GrimAC" and next commit should fix it for you.

**Comment by MWHunter** [comment]
PacketEvents.create(this);
        PacketEventsSettings settings = PacketEvents.get().getSettings();
        settings.checkForUpdates(false).bStats(true);
        PacketEvents.get().loadAsyncNewThread();

This is how I'm creating the injector onLoad()

**Comment by retrooper** [comment]
Can you test the commit I just pushed? Put the plugin.yml plugin name to "GrimAC" again.

**Comment by MWHunter** [comment]
The commit fixed the issue

**Comment by retrooper** [comment]
:+1:
